### PR TITLE
Fix Python bindings and improve Travis

### PR DESCRIPTION
**Pull request by Phyks**
* Improve Travis-CI to use the Docker architecture and check against various compilers. Build still fails due to libavresample not being available on Ubuntu 12.04.

* Update doc

* Fix Python bindings as discussed with @fossfreedom.

EDIT: I think this fixes what I had to do for the Python bindings. Let me know if you see anything else. Last thing I should do is map the unittests onto the bindings.

### CODE REVIEW

**Comment by Phyks** [comment]
@fossfreedom Build of python bindings should be more stable now. Still the same steps to get it to build. On my PC (Arch Linux, Python 2 or 3), I do not have any issue to build. Tell me if you still experience some issues under Ubuntu 14.04, I will fix them :)

**Comment by fossfreedom** [comment]
@Phyks - looks like its missing the extra_args statement to compile with std_c99

 - extra_compile_args=["-std=c99"] in build_bliss.py

**Comment by Phyks** [comment]
Indeed, my mistake. Fixed in https://github.com/Polochon-street/bliss/pull/16.

**Comment by fossfreedom** [comment]
brilliant!

many thanks :)

**Pull request merged**
